/* generated by tools/build_elf_page.py - do not edit */
window.PAYLOAD_TILES = [
    { title: "etahen", description: "Homebrew enabler and payload host.", name: "etaHEN.elf", key: "etahen" },
    { title: "onionhen", description: "Homebrew enabler and payload host.", name: "OnionHEN.elf", key: "onionhen" }
];
window.PAYLOAD_ART = { dir: "ui/", pfx: "btn-", on: true };
