var b64s = "6QAAAABTSIHsAAEAAOgdDQAA6NMHAAAxwEiJ4+i2BQAA6OoGAABIjT2JEAAA6AYGAABIjT19EAAA6H4GAAC+CQMAAEiNPWwQAADoYQYAAEiNPX8QAADo3QUAAEiNPXMQAADoVQYAAL4JAwAASI09YhAAAOg4BgAASI0NQRcAAEiJ30iNFWIQAAC+AAEAADHA/xFIid/o3gYAAEiBxAABAAAxwFvDSItXCEyLSkhMi0JASItWCGaLEmaB+vkBD4SHAgAAD4e7AAAAZoH61gEPhA0CAAB3d2aB+pYBD4S6AQAAdyZmgfqRAQ+EZwEAAGaB+pUBD4R/AQAAZoH6kAEPhUkDAADpTAEAAGaB+sIBD4SqAQAAZoH6xwEPhJ8BAABmgfqXAQ+FIwMAALmCAADADzJIidFIweEgSAnITI2Q0LTBAEgFECfWAekBAwAAZoH62gEPhKwBAAAPhqYBAABmgfr1AQ+EvgEAAGaB+vcBD4TWAQAAZoH69AEPhc4CAADpowEAAGaB+mwCD4REAgAAd1lmgforAg+E9AEAAHcmZoH6JgIPhMQBAABmgfopAg+EuQEAAGaB+vsBD4WOAgAA6YYBAABmgfpYAg+E5AEAAGaB+loCD4TZAQAAZoH6LAIPhWgCAADppgEAAGaB+p8CD4QYAgAAdyZmgfqLAg+E8QEAAGaB+p4CD4QAAgAAZoH6igIPhTUCAADp1gEAAGaB+rwCD4QFAgAAdxBmgfqgAg+E2AEAAOkTAgAAZoH6vQIPhOgBAABmgfq+Ag+E3QEAAOn4AQAAuYIAAMAPMkiJ0UjB4SBICchMjZAQdsEASAVQ6NUB6dYBAAC5ggAAwA8ySInRSMHhIEgJyEyNkOB0wQBIBSDn1QHpswEAALmCAADADzJIidFIweEgSAnITI2Q0HTBAEgFEOfVAemQAQAAuYIAAMAPMkiJ0UjB4SBICchMjZDgA9MASAVgZOoB6W0BAAC5ggAAwA8ySInRSMHhIEgJyEyNkHBy0wBIBaDR6gHpSgEAALmCAADADzJIidFIweEgSAnITI2Q4HLTAEgFENLqAeknAQAAuYIAAMAPMkiJ0UjB4SBICchMjZDghAkBSAUwGCwC6QQBAAC5ggAAwA8ySInRSMHhIEgJyEyNkOCECQFIBbAYLALp4QAAALmCAADADzJIidFIweEgSAnITI2QwD8TAUgFsPMuAum+AAAAuYIAAMAPMkiJ0UjB4SBICchMjZDAjxMBSAWwMy8C6ZsAAAC5ggAAwA8ySInRSMHhIEgJyEyNkJiSEwFIBQD5GwLre7mCAADADzJIidFIweEgSAnITI2QmNITAUgFADkcAutbuYIAAMAPMkiJ0UjB4SBICchMjZA40xMB6xi5ggAAwA8ySInRSMHhIEgJyEyNkFjjEwFIBWABMALrIbmCAADADzJIidFIweEgSAnITI2Q2OETAUgFkFUsAusBw0mLkBgBAABJx0AEAAAAAEHHQBQAAAAASL4TAAAAAAABOMcCAAAAAEmLEkmJUDBIg8r/SIsASYlBIEmJQRhIi4cwAQAASIlQYEiJcFhIiVBoMcDDSIPsCEiNFTQVAAAxwP8SWoXAD5XAD7bAw0FWQVVBVFVTSIPsMEiNLZMSAABmi1UAZoXSD4XuAAAAMcBIjXwkCrkFAAAATI0t0xIAAEiNFbQVAABmx0QkCAAASI1cJA/zqk2LZQD/EkiJ30iNFesLAABIicG+IQAAADHAQf/UTI01qhMAAEiJ30iNNeYLAABMjWQkCkH/FkiFwEiJw3UZSI01zwsAAEiNPcsLAABB/xZIhcBIicN0XUiNBeASAAC6AQAAAL50AwAASInf/xBIjQU6EwAASInZugIAAAC+AQAAAEiNfCQI/xBIjQVvEwAASInf/xAPvkwkCUiNFZQLAABED75EJAi+BQAAAEyJ5zHAQf9VAEiNBZsTAABMief/EGaJRQCJwkiDxDCJ0FtdQVxBXUFew0iD7BgxwOi//v//hcB1G+jP/v//SI09s/r//0iNdCQOZolEJA7oIgcAADHASIPEGMNIx8ADAAAA6XcKAABIx8AEAAAA6WsKAABIx8AFAAAA6V8KAABIx8AGAAAA6VMKAABIx8AKAAAA6UcKAABIx8AJAAAA6TsKAABIx8A6AAAA6S8KAABIx8A5AAAA6SMKAABIx8AVAAAA6RcKAABIx8B6AQAA6QsKAABIx8AWAAAA6f8JAABIx8B7AAAA6fMJAABIx8B8AAAA6ecJAABIx8CAAAAA6dsJAABIx8CIAAAA6c8JAABIx8CJAAAA6cMJAABIx8C8AAAA6bcJAABIx8C9AAAA6asJAABIx8C+AAAA6Z8JAABIx8AQAQAA6ZMJAABIx8DeAQAA6YcJAABIx8DtAQAA6XsJAABVU0iD7AhIjR0jEwAARTHJRTHAMckx0jH2SI09DwoAAP8TRTHJRTHAicUxyTHSMfZIjT0eCgAA/xNIjRUgEAAAie+Jw0iNNTYKAADoVQAAAEiNFRkQAACJ31hIjTVJCgAAW13pPQAAAFNIifpIgewAAgAASI0NphEAAEiJ40iJ30iNNUQKAAAxwP8RSI0Fzg8AAEiJ3r/eAAAA/xBIgcQAAgAAW8NIx8BPAgAA6coIAABIx8BQAgAA6b4IAABIg+wISInxMdJIif5FMcC/UgIAADHA6KAIAABaw0iNBU8SAABTRTHJRTHAMckx0jH2SI092QkAAP8QSI0V0g8AAEiNNeEJAACJx4nD6Jf///9IjRVjEQAAid9IjTXPCQAA6IL///9IjRXODwAAid9IjTW/CQAA6G3///9IjRUxEAAAid9IjTWxCQAA6Fj///9IjRXEEAAAid9IjTWkCQAA6EP///9IjRVvEAAAid9IjTWYCQAA6C7///9IjRU6DwAAid9IjTWKCQAA6Bn///9IjRX1DwAAid9IjTV8CQAA6AT///9IjRXwDgAAid9IjTVuCQAA6O/+//9IjRWrDwAAid9IjTVgCQAA6Nr+//9IjRVWDwAAid9IjTVTCQAA6MX+//9IjRWxDwAAid9IjTVFCQAA6LD+//9IjRVcEAAAid9IjTU4CQAA6Jv+//9IjRX3DwAAid9IjTUqCQAA6Ib+//9IjRU6DwAAid9IjTUcCQAA6HH+//9IjRXlDwAAid9IjTUPCQAA6Fz+//9IjRVgDgAAid9IjTUCCQAA6Ef+//9IjRUrDwAAid9IjTX2CAAA6DL+//9IjRXmDwAAid9IjTXoCAAA6B3+//9IjRVhDgAAid9IjTXaCAAA6Aj+//9IjRWcDgAAid9IjTXNCAAA6PP9//9IjRX3DgAAid9IjTW/CAAA6N79//9IjRWyDgAAid9IjTWxCAAA6Mn9//9IjRXVDgAAid9IjTWkCAAA6LT9//9IjRUIDgAAid9IjTWOCAAA6J/9//9IjRUrDwAAid9IjTWACAAA6Ir9//9IjRUmDwAAid9IjTVzCAAA6HX9//9IjRXRDQAAid9IjTVjCAAA6GD9//9IjRUMDgAAid9IjTVTCAAA6Ev9//9IjRVHDQAAid9IjTVGCAAA6Db9//9IjRWaDQAAid9IjTU6CAAA6CH9//9IjRUdDgAAid9IjTUwCAAA6Az9//9IjRXYDQAAid9IjTUiCAAA6Pf8//9IjRUzDgAAid9IjTUTCAAA6OL8//9IjRV+DQAAid9IjTX/BwAA6M38//9IjRXBDAAAid9IjTXvBwAA6Lj8//9IjRXUDQAAid9IjTXiBwAA6KP8//9IjRUXDQAAid9IjTXHBwAA6I78//9IjRUKDgAAid9IjTW6BwAA6Hn8//9IjRXFDQAAid9IjTWeBwAA6GT8//9IjRUIDgAAid9IjTWYBwAA6E/8//9IjRWzDQAAid9IjTWKBwAA6Dr8//9IjRVeDQAAid9IjTV+BwAA6CX8//9IjRWpDQAAid9IjTVzBwAA6BD8//9IjRWcDAAAid9IjTVqBwAA6Pv7//9IjRVPDQAAid9IjTVcBwAA6Ob7//9IjRUiDAAAid9IjTVPBwAA6NH7//9IjRX9CwAAid9IjTVCBwAA6Lz7//9IjRWADQAAid9IjTU3BwAA6Kf7//9IjRW7CwAAid9IjTUqBwAA6JL7//9IjRWuCwAAid9IjTUdBwAA6H37//9IjRU5DQAAid9IjTUSBwAA6Gj7//9IjRUMDAAAid9IjTUGBwAA6FP7//9IjRWHCwAAid9IjTX3BgAA6D77//9IjRVSDAAAid9IjTXuBgAA6Cn7//9IjRUdDAAAid9IjTXfBgAA6BT7//9IjRWoDAAAid9IjTXQBgAA6P/6//9IjRWDCwAAid9IjTXCBgAA6Or6//9IjRUeDAAAid9IjTWzBgAA6NX6//9IjRUZDAAAid9IjTWkBgAA6MD6//+J30iNFSoLAABbSI01lQYAAOmq+v//SMfAJQAAAOl0AwAASMfANgAAAOloAwAASMfACwAAAOlcAwAAVVNIg+wISI0dZAwAAEiNLd0MAABIjT1ZBgAASIneSMdFAAAAAADoc/r//4XAdCJIid5IjT1KBgAA6GD6//+FwHQPSIneSI09SgYAAOhN+v//iztIjTVPBgAASI0VGAwAAOgg+v//iztIjTVMBgAASI0VQwwAAOgL+v//iztIiepIjTVFBgAA6Pr5//+LO0iNNT8GAABIjRU1DAAA6OX5//+LO0iNNTkGAABIjRVgDAAA6ND5//+LO0iNNT0GAABIjRV7DAAA6Lv5//+LO0iNNUYGAABIjRXmCwAA6Kb5//+LO0iNNUoGAABIjRWRCwAA6JH5//+LO0iNNVIGAABIjRUEDAAA6Hz5//+LO0iNNUsGAABIjRVPDAAA6Gf5//+LO0iNNUQGAABIjRWyCwAA6FL5//+LO0iNNT0GAABIjRW9CwAA6D35//+LO0iNNTcGAABIjRXICwAA6Cj5//+LO0iNNTEGAABIjRUrCwAA6BP5//+LO0iNNSsGAABIjRXGCwAA6P74//+LO0iNNSYGAABIjRXJCgAA6On4//+LO0iNNScGAABIjRWECwAA6NT4//+LO0iNNSoGAABIjRXfCgAA6L/4//+LO0iNNSwGAABIjRUCCwAA6Kr4//+LO0iNNR4GAABIjRWdCwAA6JX4//+LO0iNNRYGAABIjRXICgAA6ID4//+LO0iNNQkGAABIjRVzCgAA6Gv4//+LO0iNNfsFAABIjRUuCwAA6Fb4//+LO0iNNfMFAABIjRXpCgAA6EH4//+LO0iNNfUFAABIjRUMCwAA6Cz4//+LO0iNNfYFAABIjRU/CgAA6Bf4//+LO0iNNfcFAABIjRXSCgAA6AL4//+LO0iNNfgFAABIjRXtCgAA6O33//+LO0iNNfkFAABIjRUICgAA6Nj3//+LO0iNNesFAABIjRWrCQAA6MP3//+LO0iNNd0FAABIjRW+CQAA6K73//+LO0iNNc8FAABIjRWJCgAA6Jn3//+LO0iNNcEFAABIjRX8CQAA6IT3//+LO0iNNbMFAABIjRUnCgAA6G/3//+LO0iNNacFAABIjRXCCQAA6Fr3//+LO0iNNZsFAABIjRU9CgAA6EX3//+LO0iNNaYFAABIjRXICQAAWFtd6S33//9IMcBJicoPBXIBw0iDPYUJAAAAdBhQ/xV8CQAAWYkISMfA/////0jHwv/////DL3VwZGF0ZS9QUzRVUERBVEUuUFVQLm5ldC50ZW1wAC91cGRhdGUvUFM0VVBEQVRFLlBVUABEaXNhYmxlZCB1cGRhdGVzIQAvJXMvY29tbW9uL2xpYi9saWJjLnNwcngAcmIAL3N5c3RlbS9jb21tb24vbGliL2xpYmMuc3ByeAAlMDJ4JTAyeAAvc3lzdGVtL2NvbW1vbi9saWIvbGliU2NlU3lzVXRpbC5zcHJ4AC9zeXN0ZW0vY29tbW9uL2xpYi9saWJTY2VTeXN0ZW1TZXJ2aWNlLnNwcngAc2NlU3lzVXRpbFNlbmRTeXN0ZW1Ob3RpZmljYXRpb25XaXRoVGV4dABzY2VTeXN0ZW1TZXJ2aWNlTGF1bmNoV2ViQnJvd3NlcgAlcwBsaWJTY2VMaWJjSW50ZXJuYWwuc3ByeABtYWxsb2MAZnJlZQBjYWxsb2MAcmVhbGxvYwBtZW1hbGlnbgBtZW1zZXQAbWVtY3B5AG1lbWNtcABzdHJjcHkAc3RybmNweQBzdHJjYXQAc3RybmNhdABzdHJsZW4Ac3RyY21wAHN0cm5jbXAAc3ByaW50ZgBzbnByaW50ZgBzc2NhbmYAc3RyY2hyAHN0cnJjaHIAc3Ryc3RyAHN0cmR1cABzdHJ0b2sAcmluZGV4AGlzZGlnaXQAYXRvaQBhdG9mAHN0cmxjcHkAc3RyZXJyb3IAX0dldHBjdHlwZQBfU3RvdWwAYmNvcHkAc3JhbmQAYXNjdGltZQBhc2N0aW1lX3IAZ210aW1lAGdtdGltZV9zAGxvY2FsdGltZQBsb2NhbHRpbWVfcgBta3RpbWUAb3BlbmRpcgByZWFkZGlyAHJlYWRkaXJfcgB0ZWxsZGlyAHNlZWtkaXIAcmV3aW5kZGlyAGNsb3NlZGlyAGRpcmZkAGdldHByb2duYW1lAGZvcGVuAGZyZWFkAGZ3cml0ZQBmc2VlawBmdGVsbABmY2xvc2UAZnByaW50ZgBsaWJrZXJuZWwuc3ByeABsaWJrZXJuZWxfd2ViLnNwcngAbGlia2VybmVsX3N5cy5zcHJ4AF9fc3RhY2tfY2hrX2d1YXJkAF9fc3RhY2tfY2hrX2ZhaWwAX19lcnJvcgBzY2VLZXJuZWxFcnJvcgBzY2VLZXJuZWxMb2FkU3RhcnRNb2R1bGUAc2NlS2VybmVsQWxsb2NhdGVEaXJlY3RNZW1vcnkAc2NlS2VybmVsTWFwRGlyZWN0TWVtb3J5AHNjZUtlcm5lbEdldERpcmVjdE1lbW9yeVNpemUAc2NlS2VybmVsU3RhdABzY2VLZXJuZWxPcGVuAHNjZUtlcm5lbFJlYWQAc2NlS2VybmVsTHNlZWsAc2NlS2VybmVsQ2xvc2UAc2NlS2VybmVsU2xlZXAAc2NlS2VybmVsVXNsZWVwAHNjZUtlcm5lbEdldHRpbWVvZmRheQBzY2VLZXJuZWxHZXRQcm9jZXNzVGltZQBzY2VLZXJuZWxHZXRDdXJyZW50Q3B1AHN5c2N0bABzeXNjdGxieW5hbWUAc3lzYXJjaABleGVjdmUAcHRocmVhZF9zZWxmAHB0aHJlYWRfc2V0YWZmaW5pdHlfbnAAc2NlS2VybmVsQ3JlYXRlRXF1ZXVlAHNjZUtlcm5lbERlbGV0ZUVxdWV1ZQBzY2VLZXJuZWxBZGRVc2VyRXZlbnQAc2NlS2VybmVsQWRkUmVhZEV2ZW50AGdldHVpZABnZXRnaWQAZ2V0cGlkAHNldHVpZABzZXRnaWQAc2V0cmV1aWQAc2V0cmVnaWQAc2NlS2VybmVsR2V0RnNTYW5kYm94UmFuZG9tV29yZABzY2VLZXJuZWxHZXRTeXN0ZW1Td1ZlcnNpb24AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9f7/bwAAAABgFiAmCQAAAAUAAAAAAAAAWBYgJgkAAAAGAAAAAAAAAEAWICYJAAAACgAAAAAAAAABAAAAAAAAAAsAAAAAAAAAGAAAAAAAAAAVAAAAAAAAAAAAAAAAAAAAHgAAAAAAAAAIAAAAAAAAAPv//28AAAAAAQAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

var Base64Binary = {
	_keyStr : "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",
	
	/* will return a  Uint8Array type */
	decodeArrayBuffer: function(input) {
		var bytes = (input.length/4) * 3;
		var ab = new ArrayBuffer(bytes);
		return this.decode(input, ab);
	},

	removePaddingChars: function(input){
		var lkey = this._keyStr.indexOf(input.charAt(input.length - 1));
		if(lkey == 64){
			return input.substring(0,input.length - 1);
		}
		return input;
	},

	decode: function (input, arrayBuffer) {
		//get last chars to see if are valid
		input = this.removePaddingChars(input);
		input = this.removePaddingChars(input);

		var bytes = parseInt((input.length / 4) * 3, 10);
		
		var uarray;
		var chr1, chr2, chr3;
		var enc1, enc2, enc3, enc4;
		var i = 0;
		var j = 0;
		
		if (arrayBuffer)
			uarray = new Uint8Array(arrayBuffer);
		else
			uarray = new Uint8Array(bytes);
		
		input = input.replace(/[^A-Za-z0-9\+\/\=]/g, "");
		
		for (i=0; i<bytes; i+=3) {	
			//get the 3 octects in 4 ascii chars
			enc1 = this._keyStr.indexOf(input.charAt(j++));
			enc2 = this._keyStr.indexOf(input.charAt(j++));
			enc3 = this._keyStr.indexOf(input.charAt(j++));
			enc4 = this._keyStr.indexOf(input.charAt(j++));
	
			chr1 = (enc1 << 2) | (enc2 >> 4);
			chr2 = ((enc2 & 15) << 4) | (enc3 >> 2);
			chr3 = ((enc3 & 3) << 6) | enc4;
	
			uarray[i] = chr1;			
			if (enc3 != 64) uarray[i+1] = chr2;
			if (enc4 != 64) uarray[i+2] = chr3;
		}
	
		return uarray;	
	}
}

function write_payload(payload_writer)
{
	var ua = Base64Binary.decode(b64s);

	var i;
	for (i = 0; i < ua.length; i++) {
		payload_writer[i] = ua[i];
	}
}
