var b64s = "6QAAAABTSIn76H0KAADoYAUAAEiNNTQAAABIidq/CwAAADHA6B4OAADoCwEAAEiNPUAOAADoaAEAADHAW8NIifkPMkiJ10jB5yBICfjDSItHCLmCAADASItwQEyLQEgPMkiJ0UiLlhgBAABIweEgSAnBSI2BQP7//0jHRgQAAAAAx0YUAAAAAEiDyf/HAgAAAABIi5CY4xMBSIlWMEiLkFBXLAJJiVAgSYlQGEiLlzABAABIvwcAAAAAAAA4SIlKYEiJelhIiUpoDyDCSInRSIHh///+/w8iwceA/vUlAAEAmQnHgHkFJgABAJkJx4AaBiYAAQCZCceAqFJmAAEAmQnHgKL3awABAJkJx4DUjncAAQCZCceAGnp4AAEAmQnHgIDEqAEBAJkJx4BoBR8CAQCZCQ8iwjHAw1VTSIPsCEUxyUUxwDHJMdIx9kiNPT0NAAD/FRAXAABFMclFMcCJxTHJMdIx9kiNPUgNAAD/FfUWAACJ70iNFSQUAACJw0iNNVwNAADoSwMAAFiJ31tIjRUbFAAAXUiNNW0NAADpMwMAAFNIifpIgewAAgAASI01dw0AAEiJ4zHASInf/xWWFQAASInev94AAAD/FdATAABIgcQAAgAAW8Mx9v8lzxMAAFNFMclIg+wQRTHAMckx0jH2SI09NQ0AAP8VaRYAAEiNFZITAABIjTVLDQAAicOJx+i/AgAASI0VoxMAAEiNNU0NAACJ3+iqAgAASI0VlhMAAEiNNVkNAACJ3+iVAgAAMf//FVATAACFwHUTSInn/xVrEwAAhcB1Bv8VaRMAAEiLBCRIi1QkCEiDxBBbw1NFMclIg+wQRTHAMckx0jH2SI09qAwAAP8V3BUAAEiNFQUTAABIjTW+DAAAicOJx+gyAgAASI0VFhMAAEiNNcAMAACJ3+gdAgAASI0VCRMAAEiNNcwMAACJ3+gIAgAAMf//FcMSAACFwHQFg8j/6x5Iief/FdkSAACFwHXugzwk/3ToMcD/Fc8SAACLBCRIg8QQW8NBVFVTQYn8SIPsIL8QAAAA/xUAEwAARTHJRTHAMckx0jH2SI09AwwAAEiJw/8VNBUAAEiNFV0SAABIjTUWDAAAicWJx+iKAQAASI0VZhIAAEiNNVEMAACJ7+h1AQAASI0VYRIAAEiNNSQMAACJ7+hgAQAAMf//FRsSAACFwHUwSI1sJA+6EQAAAEiJ7kSJ5/8VIRIAAIXAdRZIie5Iid//FTkSAAAxwP8VGRIAAOsCMdtIg8QgSInYW11BXMNTRTHJSIPsEEUxwDHJMdIx9kiNPVcLAAD/FYsUAABIjRXEEQAASI012QsAAInDicfo4QAAAEiNFZ0RAABIjTVWCwAAid/ozAAAAEiNFbgRAABIjTV7CwAAid/otwAAADH//xVyEQAAhcB1GUiNfCQM/xVzEQAAhcB1Cv8ViREAAItEJAxIg8QQW8NTSI01kAsAAL8cAgAAMcDo6gkAALoAQAAAMclIicOJxr8iAgAAMcDo0gkAAInevx0CAAAxwOjECQAAW7oeAAAAvgEAAAC/JQAAADHA6a0JAABIg+wIRTHJRTHAMckx0jH2SI09QQsAAP8VsRMAAEiNFRIRAABIjTVPCwAAicfoCQAAAFoxwP8l+xAAAEjHwE8CAADpaQkAAEjHwFACAADpXQkAAEiD7AhIxwZgAQAASInyMcCJ/r9RAgAA6D4JAABaw0iD7AhIifEx0kiJ/kUxwL9SAgAAMcDoIQkAAFrDSIPsCIn+MdIxyb9TAgAAMcDoCQkAAFrDSIPsCDHSMfZIjT3VCgAARTHJRTHAMcn/FQsTAABIjRV0EAAASI01zgoAAInHWOli////U0UxyUUxwDHJMdIx9kiNPckKAAD/FdsSAABIjRWEEAAASI01zQoAAInDicfoMf///4nfSI0VAxIAAEiNNbsKAADoHP///4nfSI0VfhAAAEiNNasKAADoB////4nfSI0V2RAAAEiNNZ0KAADo8v7//4nfSI0VZBEAAEiNNZAKAADo3f7//4nfSI0VDxEAAEiNNYQKAADoyP7//4nfSI0V6g8AAEiNNXYKAADos/7//4nfSI0VlRAAAEiNNWgKAADonv7//4nfSI0VoA8AAEiNNVoKAADoif7//4nfSI0VUxAAAEiNNUwKAADodP7//4nfSI0V/g8AAEiNNT8KAADoX/7//4nfSI0VURAAAEiNNTEKAADoSv7//4nfSI0V/BAAAEiNNSQKAADoNf7//4nfSI0VlxAAAEiNNRYKAADoIP7//4nfSI0V4g8AAEiNNQgKAADoC/7//4nfSI0VhRAAAEiNNfsJAADo9v3//4nfSI0VEA8AAEiNNe4JAADo4f3//4nfSI0Vyw8AAEiNNeIJAADozP3//4nfSI0VhhAAAEiNNdQJAADot/3//4nfSI0VEQ8AAEiNNcYJAADoov3//4nfSI0VRA8AAEiNNbkJAADojf3//4nfSI0Vlw8AAEiNNasJAADoeP3//4nfSI0Vig8AAEiNNZ4JAADoY/3//4nfSI0VzQ4AAEiNNYgJAADoTv3//4nfSI0V4A8AAEiNNXoJAADoOf3//4nfSI0V2w8AAEiNNW0JAADoJP3//4nfSI0V3g4AAEiNNV0JAADoD/3//4nfSI0VIQ4AAEiNNVAJAADo+vz//4nfSI0VbA4AAEiNNUQJAADo5fz//4nfSI0V5w4AAEiNNToJAADo0Pz//4nfSI0Vqg4AAEiNNSwJAADou/z//4nfSI0V/Q4AAEiNNR0JAADopvz//4nfSI0VUA4AAEiNNQkJAADokfz//4nfSI0Vmw0AAEiNNfkIAADofPz//4nfSI0Vng4AAEiNNewIAADoZ/z//4nfSI0V6Q0AAEiNNdEIAADoUvz//4nfSI0V1A4AAEiNNcQIAADoPfz//4nfSI0Vjw4AAEiNNagIAADoKPz//4nfSI0V0g4AAEiNNaIIAADoE/z//4nfSI0VfQ4AAEiNNZQIAADo/vv//4nfSI0VKA4AAEiNNYgIAADo6fv//4nfSI0Vcw4AAEiNNX0IAADo1Pv//4nfSI0Vbg0AAEiNNXQIAADov/v//4nfSI0VGQ4AAEiNNWYIAADoqvv//4nfSI0V/AwAAEiNNVkIAADolfv//4nfSI0V1wwAAEiNNUwIAADogPv//4nfSI0VSg4AAEiNNUEIAADoa/v//4nfSI0VlQwAAEiNNTQIAADoVvv//4nfSI0ViAwAAEiNNScIAADoQfv//4nfSI0VAw4AAEiNNRwIAADoLPv//4nfSI0V3gwAAEiNNRAIAADoF/v//4nfSI0VYQwAAEiNNQEIAADoAvv//4nfSI0VHA0AAEiNNfgHAADo7fr//4nfSI0V5wwAAEiNNekHAADo2Pr//4nfSI0Vcg0AAEiNNdoHAADow/r//4nfSI0VVQwAAEiNNcwHAADorvr//4nfSI0V6AwAAEiNNb0HAADomfr//4nfSI0V4wwAAEiNNa4HAADohPr//4nfW0iNFf0LAABIjTWfBwAA6W76//9Ix8AlAAAA6dcDAABIx8A2AAAA6csDAABIx8ALAAAA6b8DAABIg+wISI01Mg0AAEiNPWgFAABIxwWgDQAAAAAAAOhe+v//hcB0KkiNNRANAABIjT1KBwAA6Ef6//+FwHQTSI01+QwAAEiNPUYHAADoMPr//4s95wwAAEiNFegMAABIjTVABwAA6OH5//+LPc4MAABIjRUPDQAASI01OQcAAOjI+f//iz21DAAASI0VLg0AAEiNNTEHAADor/n//4s9nAwAAEiNFfUMAABIjTUgBwAA6Jb5//+LPYMMAABIjRUcDQAASI01FgcAAOh9+f//iz1qDAAASI0VKw0AAEiNNRYHAADoZPn//4s9UQwAAEiNFZoMAABIjTUbBwAA6Ev5//+LPTgMAABIjRVBDAAASI01GwcAAOgy+f//iz0fDAAASI0VsAwAAEiNNR8HAADoGfn//4s9BgwAAEiNFe8MAABIjTUUBwAA6AD5//+LPe0LAABIjRVWDAAASI01CQcAAOjn+P//iz3UCwAASI0VXQwAAEiNNf4GAADozvj//4s9uwsAAEiNFVwMAABIjTX0BgAA6LX4//+LPaILAABIjRXDCwAASI016gYAAOic+P//iz2JCwAASI0VUgwAAEiNNeAGAADog/j//4s9cAsAAEiNFVkLAABIjTXXBgAA6Gr4//+LPVcLAABIjRUIDAAASI011AYAAOhR+P//iz0+CwAASI0VZwsAAEiNNdMGAADoOPj//4s9JQsAAEiNFYYLAABIjTXRBgAA6B/4//+LPQwLAABIjRUNDAAASI01vwYAAOgG+P//iz3zCgAASI0VRAsAAEiNNbMGAADo7ff//4s92goAAEiNFesKAABIjTWiBgAA6NT3//+LPcEKAABIjRWaCwAASI01kAYAAOi79///iz2oCgAASI0VUQsAAEiNNYQGAADoovf//4s9jwoAAEiNFXALAABIjTWCBgAA6In3//+LPXYKAABIjRWnCgAASI01fwYAAOhw9///iz1dCgAASI0VLgsAAEiNNXwGAADoV/f//4s9RAoAAEiNFT0LAABIjTV5BgAA6D73//+LPSsKAABIjRVkCgAASI01dgYAAOgl9///iz0SCgAASI0VAwoAAEiNNWQGAADoDPf//4s9+QkAAEiNFRIKAABIjTVSBgAA6PP2//+LPeAJAABIjRXRCgAASI01QAYAAOja9v//iz3HCQAASI0VSAoAAEiNNS4GAADowfb//4s9rgkAAEiNFWcKAABIjTUcBgAA6Kj2//+LPZUJAABIjRUGCgAAWEiNNQsGAADpjvb//0gxwEmJyg8FcgHDSIM97gkAAAB0GFD/FeUJAABZiQhIx8D/////SMfC/////8NTcG9vZiB0byA5Ljk5IEZXIGJ5IEthcm8uAC9zeXN0ZW0vY29tbW9uL2xpYi9saWJTY2VTeXNVdGlsLnNwcngAL3N5c3RlbS9jb21tb24vbGliL2xpYlNjZVN5c3RlbVNlcnZpY2Uuc3ByeABzY2VTeXNVdGlsU2VuZFN5c3RlbU5vdGlmaWNhdGlvbldpdGhUZXh0AHNjZVN5c3RlbVNlcnZpY2VMYXVuY2hXZWJCcm93c2VyACVzAC9zeXN0ZW0vY29tbW9uL2xpYi9saWJTY2VVc2VyU2VydmljZS5zcHJ4AHNjZVVzZXJTZXJ2aWNlSW5pdGlhbGl6ZQBzY2VVc2VyU2VydmljZUdldExvZ2luVXNlcklkTGlzdABzY2VVc2VyU2VydmljZVRlcm1pbmF0ZQBzY2VVc2VyU2VydmljZUdldFVzZXJOYW1lAHNjZVVzZXJTZXJ2aWNlR2V0SW5pdGlhbFVzZXIAU2NlU3lzQ29yZVJlYm9vdAAvc3lzdGVtL2NvbW1vbi9saWIvbGlia2VybmVsLnNwcngAc2NlS2VybmVsUmVib290AGxpYlNjZVN5c21vZHVsZS5zcHJ4AHNjZVN5c21vZHVsZUxvYWRNb2R1bGUAbGliU2NlTGliY0ludGVybmFsLnNwcngAbWFsbG9jAGZyZWUAY2FsbG9jAHJlYWxsb2MAbWVtYWxpZ24AbWVtc2V0AG1lbWNweQBtZW1jbXAAc3RyY3B5AHN0cm5jcHkAc3RyY2F0AHN0cm5jYXQAc3RybGVuAHN0cmNtcABzdHJuY21wAHNwcmludGYAc25wcmludGYAc3NjYW5mAHN0cmNocgBzdHJyY2hyAHN0cnN0cgBzdHJkdXAAcmluZGV4AGlzZGlnaXQAYXRvaQBzdHJsY3B5AHN0cmVycm9yAF9HZXRwY3R5cGUAX1N0b3VsAGJjb3B5AHNyYW5kAGFzY3RpbWUAYXNjdGltZV9yAGdtdGltZQBnbXRpbWVfcwBsb2NhbHRpbWUAbG9jYWx0aW1lX3IAbWt0aW1lAG9wZW5kaXIAcmVhZGRpcgByZWFkZGlyX3IAdGVsbGRpcgBzZWVrZGlyAHJld2luZGRpcgBjbG9zZWRpcgBkaXJmZABnZXRwcm9nbmFtZQBmb3BlbgBmcmVhZABmd3JpdGUAZnNlZWsAZnRlbGwAZmNsb3NlAGZwcmludGYAbGlia2VybmVsX3dlYi5zcHJ4AGxpYmtlcm5lbF9zeXMuc3ByeABfX3N0YWNrX2Noa19ndWFyZABfX3N0YWNrX2Noa19mYWlsAF9fZXJyb3IAc2NlS2VybmVsRXJyb3IAc2NlS2VybmVsTG9hZFN0YXJ0TW9kdWxlAHNjZUtlcm5lbEFsbG9jYXRlRGlyZWN0TWVtb3J5AHNjZUtlcm5lbE1hcERpcmVjdE1lbW9yeQBzY2VLZXJuZWxHZXREaXJlY3RNZW1vcnlTaXplAHNjZUtlcm5lbFN0YXQAc2NlS2VybmVsT3BlbgBzY2VLZXJuZWxSZWFkAHNjZUtlcm5lbExzZWVrAHNjZUtlcm5lbENsb3NlAHNjZUtlcm5lbFNsZWVwAHNjZUtlcm5lbFVzbGVlcABzY2VLZXJuZWxHZXR0aW1lb2ZkYXkAc2NlS2VybmVsR2V0UHJvY2Vzc1RpbWUAc2NlS2VybmVsR2V0Q3VycmVudENwdQBzeXNjdGwAc3lzY3RsYnluYW1lAHN5c2FyY2gAZXhlY3ZlAHB0aHJlYWRfc2VsZgBwdGhyZWFkX3NldGFmZmluaXR5X25wAHNjZUtlcm5lbENyZWF0ZUVxdWV1ZQBzY2VLZXJuZWxEZWxldGVFcXVldWUAc2NlS2VybmVsQWRkVXNlckV2ZW50AHNjZUtlcm5lbEFkZFJlYWRFdmVudABnZXR1aWQAZ2V0Z2lkAGdldHBpZABzZXR1aWQAc2V0Z2lkAHNldHJldWlkAHNldHJlZ2lkAC9saWI2NC9sZC1saW51eC14ODYtNjQuc28uMgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9f7/bwAAAACYFCAmCQAAAAUAAAAAAAAAkBQgJgkAAAAGAAAAAAAAAHgUICYJAAAACgAAAAAAAAABAAAAAAAAAAsAAAAAAAAAGAAAAAAAAAAVAAAAAAAAAAAAAAAAAAAAHgAAAAAAAAAIAAAAAAAAAPv//28AAAAAAQAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

var Base64Binary = {
	_keyStr : "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",
	
	/* will return a  Uint8Array type */
	decodeArrayBuffer: function(input) {
		var bytes = (input.length/4) * 3;
		var ab = new ArrayBuffer(bytes);
		return this.decode(input, ab);
	},

	removePaddingChars: function(input){
		var lkey = this._keyStr.indexOf(input.charAt(input.length - 1));
		if(lkey == 64){
			return input.substring(0,input.length - 1);
		}
		return input;
	},

	decode: function (input, arrayBuffer) {
		//get last chars to see if are valid
		input = this.removePaddingChars(input);
		input = this.removePaddingChars(input);

		var bytes = parseInt((input.length / 4) * 3, 10);
		
		var uarray;
		var chr1, chr2, chr3;
		var enc1, enc2, enc3, enc4;
		var i = 0;
		var j = 0;
		
		if (arrayBuffer)
			uarray = new Uint8Array(arrayBuffer);
		else
			uarray = new Uint8Array(bytes);
		
		input = input.replace(/[^A-Za-z0-9\+\/\=]/g, "");
		
		for (i=0; i<bytes; i+=3) {	
			//get the 3 octects in 4 ascii chars
			enc1 = this._keyStr.indexOf(input.charAt(j++));
			enc2 = this._keyStr.indexOf(input.charAt(j++));
			enc3 = this._keyStr.indexOf(input.charAt(j++));
			enc4 = this._keyStr.indexOf(input.charAt(j++));
	
			chr1 = (enc1 << 2) | (enc2 >> 4);
			chr2 = ((enc2 & 15) << 4) | (enc3 >> 2);
			chr3 = ((enc3 & 3) << 6) | enc4;
	
			uarray[i] = chr1;			
			if (enc3 != 64) uarray[i+1] = chr2;
			if (enc4 != 64) uarray[i+2] = chr3;
		}
	
		return uarray;	
	}
}

function write_payload(payload_writer)
{
	var ua = Base64Binary.decode(b64s);

	var i;
	for (i = 0; i < ua.length; i++) {
		payload_writer[i] = ua[i];
	}
}
